In [2]:
import numpy as np

In [7]:
calorie_array=np.array([[56, 0, 4.4, 68],[1.2, 104, 52, 8],[1.8, 135, 99, 0.9]])

In [10]:
np.sum(calorie_array, axis=0)

array([ 59. , 239. , 155.4,  76.9])

In [11]:
calorie_array/np.sum(calorie_array, axis=0)

array([[0.94915254, 0.        , 0.02831403, 0.88426528],
       [0.02033898, 0.43514644, 0.33462033, 0.10403121],
       [0.03050847, 0.56485356, 0.63706564, 0.01170351]])

In [3]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [4]:
np.dot(a,b)

array([[-0.98350301,  2.24121638],
       [-1.04947511,  2.34659154],
       [-0.41810494,  0.18962964],
       [ 1.40799525, -2.16470909]])

In [5]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [6]:
c.shape

(2, 3)

In [7]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [8]:
c.shape

(3, 3)